# -*- coding: utf-8 -*-
"""23IE10036_P1_SAYAK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cycnnK31enOW53DiLzoXhO18Zyc0v87b
"""

# import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import os

# load dataset
df = pd.read_csv('data_insurance.csv')

# explore the data
print("="*50)
print("===== 1. Initial Data Exploration =====")
print("="*50)
print("\n--- First 5 Rows of the Dataset ---")
print(df.head())
print("\n--- Dataset Info (Data Types and Nulls) ---")
print(df.info())
print("\n--- Summary Statistics ---")
print(df.describe())

# Convert Categorical Variables
df['smoker'] = df['smoker'].map({'yes': 1, 'no': 0})
df['sex'] = df['sex'].map({'female': 1, 'male': 0})
region_map = {
    'southwest': 1,
    'southeast': 2,
    'northwest': 3,
    'northeast': 4
}
df['region'] = df['region'].map(region_map)

# Explore converted data
print("\n" + "="*50)
print("===== 2. Data After Manual Encoding =====")
print("="*50)
print("\n--- First 5 Rows After Encoding ---")
print(df.head())
print("\n--- Dataset Info After Encoding ---")
print(df.info())
print("\n--- Summary Statistics After Encoding ---")
print(df.describe())

# Define Features and Target
X = df.drop('charges', axis=1)
y = df['charges']

# Split the Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

# Make Predictions
y_pred = model.predict(X_test)

# Evaluate the Model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared: {r2:.4f}")
print(f"Root Mean Squared Error (RMSE): ${rmse:.2f}")

# Analyze Model Coefficients
coefficients = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
print(coefficients)# Evaluate the Model
print("\n" + "="*50)
print("===== 3. Initial Model Performance =====")
print("="*50)
mse1 = mean_squared_error(y_test, y_pred)
r2_1 = r2_score(y_test, y_pred)
rmse1 = np.sqrt(mse1)

print(f"Mean Squared Error: {mse1:.2f}")
print(f"R-squared: {r2_1:.4f}")
print(f"Root Mean Squared Error (RMSE): ${rmse1:.2f}")

# Analyze Model Coefficients
print("\n--- Initial Model Coefficients ---")
coefficients1 = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
print(coefficients1)

############ Model Refinement ############
X_new = X

# Add Interaction Terms
X_new['bmi_smoker'] = X_new['bmi'] * X_new['smoker']
X_new['region_children'] = X_new['region'] * X_new['children']

#  Adjust Features (Feature Selection)
X_new = X_new.drop(['children', 'sex', 'bmi'], axis = 1)

# Explore new Dataset
print("\n" + "="*50)
print("===== 4. Data After Feature Engineering =====")
print("="*50)
print("\n--- First 5 Rows of the New Feature Set (X_new) ---")
print(X_new.head())

# Split Dataset
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_new, y, test_size=0.2, random_state=42)

# Train the Linear Regression Model
model = LinearRegression()
model.fit(X_train1, y_train1)

# Make Predictions
y_pred1 = model.predict(X_test1)

# Evaluate the model
print("\n" + "="*50)
print("===== 5. Refined Model Performance =====")
print("="*50)
mse2 = mean_squared_error(y_test1, y_pred1)
r2_2 = r2_score(y_test1, y_pred1)
rmse2 = np.sqrt(mse2)

print(f"Mean Squared Error: {mse2:.2f}")
print(f"R-squared: {r2_2:.4f}")
print(f"Root Mean Squared Error (RMSE): ${rmse2:.2f}")

# Analyze the Model
print("\n--- Refined Model Coefficients ---")
coefficients2 = pd.DataFrame(model.coef_, X_new.columns, columns=['Coefficient'])
print(coefficients2)

# =======================================================
# ========== SAVING OUTPUTS TO A FILE ===================
# =======================================================

# Open the file in 'write' mode to save the first model's output
with open('output.txt', 'w') as f:
    f.write("="*50 + "\n")
    f.write("===== Initial Model Performance =====\n")
    f.write("="*50 + "\n")

    f.write(f"Mean Squared Error: {mse1:.2f}\n")
    f.write(f"R-squared: {r2_1:.4f}\n")
    f.write(f"Root Mean Squared Error (RMSE): ${rmse1:.2f}\n\n")

    # Analyze Model Coefficients
    f.write("--- Initial Model Coefficients ---\n")
    f.write(coefficients1.to_string()) # .to_string() converts the DataFrame to text


    f.write("\n\n" + "="*50 + "\n")
    f.write("===== Refined Model Performance =====\n")
    f.write("="*50 + "\n")


    f.write(f"Mean Squared Error: {mse2:.2f}\n")
    f.write(f"R-squared: {r2_2:.4f}\n")
    f.write(f"Root Mean Squared Error (RMSE): ${rmse2:.2f}\n\n")

    # Analyze the Model
    f.write("--- Refined Model Coefficients ---\n")
    f.write(coefficients2.to_string())

print("\n Successfully wrote all model outputs to output.txt")
os.startfile('output.txt')